version: '3.4'
services:
  dev:
    image: webpronl/reveal-md
    command: /slides --watch --port 8000 --css custom.css
    ports: &ports
      - 8000:8000
      - 35729:35729
    volumes: &vol
      - ./:/slides

  static:
    image: webpronl/reveal-md
    command: /slides --static docs --css custom.css
    volumes: *vol
